exclude_paths:
  - "migrations/"
  - "docs-source/"
  - "docs/"
engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 50
    exclude_paths:
      - "migrations/"
      - "test/**/*-test.js"
  eslint:
    channel: eslint-4
    enabled: true
  fixme:
    enabled: true
  # nodesecurity:
  #   enabled: true
ratings:
   paths:
     - "**.js"
